name: OreGen
author: Xenophilicy
version: 1.2.3
main: Xenophilicy\OreGen\OreGen
api: 3.0.0
description: Generate ores inside a cobble generator!
commands:
  oregen:
    description: Get info on OreGen
    permission: oregen.info
permissions:
  oregen.info:
    default: op