# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/

# This is where you set the probability (out of 100) that the player will get the default cobblestone
# The cobble probability and the selected ores must have a sum equal to 100 for the plugin to function
Cobble-Probability: 45

# Here you control which blocks you want players to have a chance of getting
# Set any of them to false to disable their chance of being an outcome
Coal:
  Enabled: true
  Probability: 18

Iron:
  Enabled: true
  Probability: 10

Gold:
  Enabled: true
  Probability: 8

Lapis:
  Enabled: true
  Probability: 7

Redstone:
  Enabled: true
  Probability: 5

Emerald:
  Enabled: true
  Probability: 4

Diamond:
  Enabled: true
  Probability: 3
