# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/
VERSION: "1.2.0" # Internal use only

# These are the settings that determine which worlds to enable OreGen in
Worlds:

  # This is where you can put the list of worlds which worlds to include/exclude OreGen in
  List:
    - "Lobby"
    - "Spawn"

  # Choose the mode for the world list, options are blacklist, whitelist, or false
  # Set this to false if you want OreGen to function on all worlds
  Mode: "blacklist"

# This is where you set the probability (out of 100) that the player will get the default cobblestone
# The cobble probability and all the blocks you list must have a sum of 100 for the plugin to function
Cobble-Probability: 45

# Here you control which blocks you want players to have a chance of getting
# Set any of them to false to disable their chance of being an outcome
# Use this format below for the block listing

# Blocks:
#  "Block-ID:Block-Damage": Block-Probability
#  "Block-ID:Block-Damage": Block-Probability
#  "Block-ID:Block-Damage": Block-Probability

Blocks:
  "16:0": 18 # Coal Ore
  "15:0": 10 # Iron Ore
  "14:0": 8 # Gold Ore
  "21:0": 7 # Lapis Lazuli Ore
  "73:0": 5 # Redstone Ore
  "129:0": 4 # Emerald
  "56:0": 3 # Diamond Ore